### ISSUE TITLE
ifft module cannot be imported from scipy

### ISSUE THREAD

**Issue by Jiadalee** [kevinjohncutler/omnipose#109]
I installed the omnipose using pip and then tried to start it with command `python -m omnipose`, but got the following error:

Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\jyl51\AppData\Local\Programs\Python\Python312\Lib\site-packages\omnipose\__init__.py", line 1, in <module>
    from . import core, utils, loss, plot, misc, cli, data, gpu
  File "C:\Users\jyl51\AppData\Local\Programs\Python\Python312\Lib\site-packages\omnipose\misc.py", line 648, in <module>
    import peakdetect
  File "C:\Users\jyl51\AppData\Local\Programs\Python\Python312\Lib\site-packages\peakdetect\__init__.py", line 3, in <module>
    from .peakdetect import *
  File "C:\Users\jyl51\AppData\Local\Programs\Python\Python312\Lib\site-packages\peakdetect\peakdetect.py", line 5, in <module>
    from scipy import fft, ifft
ImportError: cannot import name 'ifft' from 'scipy' (C:\Users\jyl51\AppData\Local\Programs\Python\Python312\Lib\site-packages\scipy\__init__.py). Did you mean: 'fft'?

Seems that the 'ifft' is depreciated from the scipy? See error message screenshot below

![image](https://github.com/user-attachments/assets/1a9229eb-36ac-4eef-abdd-be57e25d6b46)

**Comment by kevinjohncutler** [comment]
@Jiadalee That is due to the peakdetect dependency, but that has been removed. I need to update the pypi release.

**Comment by Jiadalee** [comment]
@kevinjohncutler great. I was suspecting the ifft module is depreciated in python...

**Comment by Aurelien-Gg** [comment]
Possible fix (?) :
in /site-packages/peakdetect/peakdetect.py:
changing  "from scipy import fft, ifft"
to "from scipy.fft import ifft"

**Comment by josephabrams** [comment]
Removing ifft corrected the issue for me:
So I changed to:
from scipy import fft

I don't know if this breaks other features.

**Comment by carlosuc3m** [comment]
+1 in this
