### ISSUE TITLE
main() got an unexpected keyword argument 'omni_CLI'

### ISSUE THREAD

**Issue by JunMa11** [kevinjohncutler/omnipose#22]
I got this error when trining omnipose with my own dataset on cluster. 

## install

```bash
module load gcc opencv python
virtualenv omnipose && source omnipose/bin/activate
pip install -U pip
pip install torch torchvision omnipose
```

## First error

```bash
python -m omnipose --train --use_gpu --dir /home/jma/scratch/omnipose/imagesTrTif --chan 0 --n_epochs 4000 --pretrained_model None --learning_rate 0.1 --diameter 0 --batch_size 32 --RAdam --dir_above --save_each --verbose --img_filter '_img' --mask_filter '_masks'
```
```python
(omnipose) [jma@narval1 omnipose]$ python -m omnipose --train --use_gpu --dir /home/jma/scratch/omnipose/imagesTrTif --chan 0 --n_epochs 4000 --pretrained_model None --learning_rate 0.1 --diameter 0 --batch_size 2 --RAdam --dir_above --save_each --verbose --img_filter '_img' --mask_filter '_masks'
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jma/omnipose/lib/python3.8/site-packages/omnipose/__main__.py", line 1, in <module>
    from cellpose.__main__ import main
ModuleNotFoundError: No module named 'cellpose'
```

I fixed this error by `pip install cellpose`

## Second error
With the same command

```bash
python -m omnipose --train --use_gpu --dir /home/jma/scratch/omnipose/imagesTrTif --chan 0 --n_epochs 4000 --pretrained_model None --learning_rate 0.1 --diameter 0 --batch_size 2 --RAdam --dir_above --save_each --verbose --img_filter '_img' --mask_filter '_masks'
```
I got the following error. 

```python
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jma/omnipose/lib/python3.8/site-packages/omnipose/__main__.py", line 3, in <module>
    main(omni_CLI=True)
TypeError: main() got an unexpected keyword argument 'omni_CLI'
```

**Comment by kevinjohncutler** [comment]
@JunMa11 could you post your `pip list`? You do not want `pip install cellpose`, as that will grab the latest main branch of Cellpose (2.0) that is incompatible. You would want `pip install cellpose-omni`, but running `pip install omnipose` should have installed that automatically.

**Comment by JunMa11** [comment]
Thanks for your help very much.

It works on our cluster with the flag NO_GUI
