### ISSUE TITLE
ubuntu18.04-python3.8.5 install omnipose error, why pyqt6 not pyqt5?

### ISSUE THREAD

**Issue by xujinzh** [kevinjohncutler/omnipose#25]
(omnipose)
# jinzhongxu @ Dell in ~ [7:37:14] C:1
$ python --version
Python 3.8.5

(omnipose)
# jinzhongxu @ Dell in ~ [7:37:21] C:1
$ pip install omnipose
Collecting omnipose
  Using cached omnipose-0.3.5-py3-none-any.whl (87 kB)
Collecting ncolor
  Using cached ncolor-1.1.8-py3-none-any.whl (8.9 kB)
Collecting mahotas>=1.4.13
  Using cached mahotas-1.4.13-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (5.5 MB)
Collecting scikit-learn
  Using cached scikit_learn-1.1.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (31.2 MB)
Collecting mgen
  Using cached mgen-1.2.0.tar.gz (13 kB)
  Preparing metadata (setup.py) ... done
Collecting numpy>=1.22.4
  Using cached numpy-1.23.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting edt
  Using cached edt-2.3.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
Collecting numba
  Using cached numba-0.56.3-cp38-cp38-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.5 MB)
Collecting scikit-image
  Using cached scikit_image-0.19.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.0 MB)
Collecting scipy
  Using cached scipy-1.9.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.8 MB)
Collecting cellpose-omni[all]>=0.6.9
  Using cached cellpose_omni-0.7.2-py3-none-any.whl (196 kB)
Collecting opencv-python-headless
  Using cached opencv_python_headless-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (48.3 MB)
Collecting tifffile
  Using cached tifffile-2022.10.10-py3-none-any.whl (210 kB)
Collecting natsort
  Using cached natsort-8.2.0-py3-none-any.whl (37 kB)
Collecting imagecodecs
  Using cached imagecodecs-2022.9.26-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.1 MB)
Collecting fastremap
  Using cached fastremap-1.13.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.9 MB)
Collecting torch>=1.6
  Using cached torch-1.13.0-cp38-cp38-manylinux1_x86_64.whl (890.2 MB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting torch-optimizer
  Using cached torch_optimizer-0.3.0-py3-none-any.whl (61 kB)
Collecting darkdetect
  Using cached darkdetect-0.7.1-py2.py3-none-any.whl (8.2 kB)
Collecting colour
  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting omnipose-theme
  Using cached omnipose_theme-1.1.2-py3-none-any.whl (43 kB)
Collecting superqt
  Using cached superqt-0.3.8-py3-none-any.whl (64 kB)
Collecting PyQt6.sip
  Using cached PyQt6_sip-13.4.0-cp38-cp38-manylinux1_x86_64.whl (310 kB)
Collecting google-cloud-storage
  Using cached google_cloud_storage-2.5.0-py2.py3-none-any.whl (106 kB)
Collecting pyqtgraph>=0.12.4
  Using cached pyqtgraph-0.13.1-py3-none-any.whl (966 kB)
Collecting PyQt6
  Using cached PyQt6-6.4.0.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/usr/local/miniconda/envs/omnipose/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/usr/local/miniconda/envs/omnipose/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/miniconda/envs/omnipose/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/miniconda/envs/omnipose/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-rsrafrt_/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/tmp/pip-build-env-rsrafrt_/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-rsrafrt_/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 65, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-rsrafrt_/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-rsrafrt_/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-rsrafrt_/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 78, in apply_user_defaults
          self._get_qt_configuration()
        File "/tmp/pip-build-env-rsrafrt_/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 493, in _get_qt_configuration
          for line in project.read_command_pipe([self.qmake, '-query']):
        File "/tmp/pip-build-env-rsrafrt_/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 553, in read_command_pipe
          raise UserException(
      sipbuild.exceptions.UserException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xujinzh** [comment]
Successfully installed omnipose 0.3.5 on **docker image ubuntu20.04** + python 3.8.13 (+ pyqt6)

**Comment by kevinjohncutler** [comment]
I updated to pyqt6 mostly for more cross-platform support if I recall correctly. It is a little new now, but the idea is that everyone will eventually make the switch and the install will be easier. For systems with pyqt5 installed, I recommend conda or docker environments.

**Comment by tibuch** [comment]
HI @kevinjohncutler,

I am facing the same issue. How can I install omnipose without pyqt6? 

Do I need pyqt if I only want to run it headless? 

Thank you for your time!

**Comment by gouthamr321** [comment]
I am also getting @xujinzh original issue with pyqt6....... Is there a easy way to downgrade to pyqt5 (This is what I think Cellpose uses) or install without pyqt if I only want to run headlessly?
