### ISSUE TITLE
omnipose install failed

### ISSUE THREAD

**Issue by hj1998xxxx** [kevinjohncutler/omnipose#43]
Hello，
I am getting the following error when I run python -m omnipose：

(omnipose) C:\Users\Administrator>python -m omnipose
100%|████████████████████████████████████████████████████████████████████████████████| 356k/356k [00:02<00:00, 143kB/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\site-packages\omnipose\__main__.py", line 1, in <module>
    from cellpose_omni import main
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\site-packages\cellpose_omni\__init__.py", line 3, in <module>
    from .__main__ import main
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\site-packages\cellpose_omni\__main__.py", line 12, in <module>
    from cellpose_omni.gui import gui
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\site-packages\cellpose_omni\gui\gui.py", line 69, in <module>
    download_url_to_file('https://github.com/kevinjohncutler/omnipose/blob/main/docs/test_files/'+file+'?raw=true',
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\site-packages\cellpose_omni\utils.py", line 70, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\urllib\request.py", line 1354, in do_open
    r = h.getresponse()
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Administrator\.conda\envs\omnipose\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060]
Would it be possible to solve the problem？
Thanks !

Additional details:
Win 10
python version 3.8.5
Omnipose-0.4.4

**Comment by kevinjohncutler** [comment]
@hj1998xxxx Sorry for the delay. Are you still getting this error? It is probably the model downloading step, and maybe Carsen's server was down at the time.
