### ISSUE TITLE
gui error: qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by JunMa11** [kevinjohncutler/omnipose#59]
Dear Omnipose team,

Thanks for providing this awesome tool.

I followed the document to install `omnipose` in a fresh virtual environment in Ubuntu 20.04, but the gui cannot be started properly. 
Here is the error log. Any suggestions are highly appreciated. 

```bash
omnipose     
```

```bash      
GUI ERROR: No module named 'PyQt6'
GUI dependencies may not be installed (normal for first run).
Install GUI dependencies? (Note: uses PyQt6.) (y/n): y
Collecting pyqtgraph>=0.12.4
  Downloading pyqtgraph-0.13.3-py3-none-any.whl (960 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.0/961.0 kB 25.9 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.20.0 in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from pyqtgraph>=0.12.4) (1.26.1)
Installing collected packages: pyqtgraph
Successfully installed pyqtgraph-0.13.3
Collecting PyQt6.sip
  Downloading PyQt6_sip-13.6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (503 bytes)
Downloading PyQt6_sip-13.6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.whl (299 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.3/299.3 kB 10.9 MB/s eta 0:00:00
Installing collected packages: PyQt6.sip
Successfully installed PyQt6.sip-13.6.0
Collecting PyQt6
  Downloading PyQt6-6.5.3-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (2.1 kB)
Requirement already satisfied: PyQt6-sip<14,>=13.6 in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from PyQt6) (13.6.0)
Collecting PyQt6-Qt6>=6.5.0 (from PyQt6)
  Downloading PyQt6_Qt6-6.5.3-py3-none-manylinux_2_28_x86_64.whl.metadata (534 bytes)
Downloading PyQt6-6.5.3-cp37-abi3-manylinux_2_28_x86_64.whl (7.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 38.7 MB/s eta 0:00:00
Downloading PyQt6_Qt6-6.5.3-py3-none-manylinux_2_28_x86_64.whl (66.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 MB 15.2 MB/s eta 0:00:00
Installing collected packages: PyQt6-Qt6, PyQt6
Successfully installed PyQt6-6.5.3 PyQt6-Qt6-6.5.3
Collecting google-cloud-storage
  Downloading google_cloud_storage-2.12.0-py2.py3-none-any.whl.metadata (6.1 kB)
Collecting google-auth<3.0dev,>=2.23.3 (from google-cloud-storage)
  Downloading google_auth-2.23.3-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 (from google-cloud-storage)
  Downloading google_api_core-2.12.0-py3-none-any.whl.metadata (2.7 kB)
Collecting google-cloud-core<3.0dev,>=2.3.0 (from google-cloud-storage)
  Downloading google_cloud_core-2.3.3-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting google-resumable-media>=2.6.0 (from google-cloud-storage)
  Downloading google_resumable_media-2.6.0-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from google-cloud-storage) (2.31.0)
Collecting google-crc32c<2.0dev,>=1.0 (from google-cloud-storage)
  Downloading google_crc32c-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (32 kB)
Collecting googleapis-common-protos<2.0.dev0,>=1.56.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage)
  Downloading googleapis_common_protos-1.61.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0.dev0,>=3.19.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-cloud-storage)
  Downloading protobuf-4.24.4-cp37-abi3-manylinux2014_x86_64.whl.metadata (540 bytes)
Collecting cachetools<6.0,>=2.0.0 (from google-auth<3.0dev,>=2.23.3->google-cloud-storage)
  Downloading cachetools-5.3.2-py3-none-any.whl.metadata (5.2 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<3.0dev,>=2.23.3->google-cloud-storage)
  Downloading pyasn1_modules-0.3.0-py2.py3-none-any.whl (181 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 181.3/181.3 kB 13.8 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4 (from google-auth<3.0dev,>=2.23.3->google-cloud-storage)
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.3.1)
Requirement already satisfied: idna<4,>=2.5 in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2023.7.22)
Collecting pyasn1<0.6.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=2.23.3->google-cloud-storage)
  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.9/83.9 kB 10.3 MB/s eta 0:00:00
Downloading google_cloud_storage-2.12.0-py2.py3-none-any.whl (120 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.5/120.5 kB 15.5 MB/s eta 0:00:00
Downloading google_api_core-2.12.0-py3-none-any.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.4/121.4 kB 9.6 MB/s eta 0:00:00
Downloading google_auth-2.23.3-py2.py3-none-any.whl (182 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.3/182.3 kB 14.2 MB/s eta 0:00:00
Downloading google_cloud_core-2.3.3-py2.py3-none-any.whl (29 kB)
Downloading google_resumable_media-2.6.0-py2.py3-none-any.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 6.5 MB/s eta 0:00:00
Downloading cachetools-5.3.2-py3-none-any.whl (9.3 kB)
Downloading googleapis_common_protos-1.61.0-py2.py3-none-any.whl (230 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.9/230.9 kB 24.9 MB/s eta 0:00:00
Downloading protobuf-4.24.4-cp37-abi3-manylinux2014_x86_64.whl (311 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.6/311.6 kB 27.0 MB/s eta 0:00:00
Installing collected packages: pyasn1, protobuf, google-crc32c, cachetools, rsa, pyasn1-modules, googleapis-common-protos, google-resumable-media, google-auth, google-api-core, google-cloud-core, google-cloud-storage
Successfully installed cachetools-5.3.2 google-api-core-2.12.0 google-auth-2.23.3 google-cloud-core-2.3.3 google-cloud-storage-2.12.0 google-crc32c-1.5.0 google-resumable-media-2.6.0 googleapis-common-protos-1.61.0 protobuf-4.24.4 pyasn1-0.5.0 pyasn1-modules-0.3.0 rsa-4.9
Collecting omnipose-theme
  Downloading omnipose_theme-1.1.2-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.4/43.4 kB 1.9 MB/s eta 0:00:00
Installing collected packages: omnipose-theme
Successfully installed omnipose-theme-1.1.2
Collecting superqt
  Downloading superqt-0.6.1-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: packaging in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from superqt) (23.2)
Collecting pygments>=2.4.0 (from superqt)
  Downloading Pygments-2.16.1-py3-none-any.whl.metadata (2.5 kB)
Collecting qtpy>=1.1.0 (from superqt)
  Downloading QtPy-2.4.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: typing-extensions!=3.10.0.0,>=3.7.4.3 in /home/jma/anaconda3/envs/omni/lib/python3.10/site-packages (from superqt) (4.8.0)
Downloading superqt-0.6.1-py3-none-any.whl (88 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.8/88.8 kB 9.0 MB/s eta 0:00:00
Downloading Pygments-2.16.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 49.7 MB/s eta 0:00:00
Downloading QtPy-2.4.1-py3-none-any.whl (93 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.5/93.5 kB 8.2 MB/s eta 0:00:00
Installing collected packages: qtpy, pygments, superqt
Successfully installed pygments-2.16.1 qtpy-2.4.1 superqt-0.6.1
Collecting darkdetect
  Downloading darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Installing collected packages: darkdetect
Successfully installed darkdetect-0.8.0
heyyyo

2023-10-24 20:05:30,156 [INFO] WRITING LOG OUTPUT TO /home/jma/.cellpose/run.log
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, eglfs, linuxfb, minimal, minimalegl, vnc, vkkhrdisplay, offscreen, xcb.

Traceback (most recent call last):
  File "/home/jma/anaconda3/envs/omni/bin/omnipose", line 8, in <module>
    sys.exit(main())
  File "/home/jma/anaconda3/envs/omni/lib/python3.10/site-packages/omnipose/__main__.py", line 9, in main
    cellpose_omni_main(args)
  File "/home/jma/anaconda3/envs/omni/lib/python3.10/site-packages/cellpose_omni/__main__.py", line 93, in main
    subprocess.check_call([sys.executable, "-m", "omnipose"])
  File "/home/jma/anaconda3/envs/omni/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/jma/anaconda3/envs/omni/bin/python', '-m', 'omnipose']' died with <Signals.SIGABRT: 6>.

```

**Comment by JunMa11** [comment]
I'm using python 3.10.12.

Here is a list of the installed packages:

```
$ pip list           
Package                  Version
------------------------ ------------
cachetools               5.3.2
certifi                  2023.7.22
charset-normalizer       3.3.1
cmake                    3.27.7
contourpy                1.1.1
cycler                   0.12.1
darkdetect               0.8.0
edt                      2.3.1
fastremap                1.14.0
filelock                 3.12.4
fonttools                4.43.1
google-api-core          2.12.0
google-auth              2.23.3
google-cloud-core        2.3.3
google-cloud-storage     2.12.0
google-crc32c            1.5.0
google-resumable-media   2.6.0
googleapis-common-protos 1.61.0
idna                     3.4
igraph                   0.11.2
imageio                  2.31.6
Jinja2                   3.1.2
joblib                   1.3.2
kiwisolver               1.4.5
lazy_loader              0.3
lit                      17.0.3
llvmlite                 0.41.1
mahotas                  1.4.13
MarkupSafe               2.1.3
matplotlib               3.8.0
mgen                     1.2.1
mpmath                   1.3.0
natsort                  8.4.0
ncolor                   1.2.1
networkx                 3.2
numba                    0.58.1
numpy                    1.26.1
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
omnipose                 1.0.6
omnipose-theme           1.1.2
opencv-python-headless   4.8.1.78
packaging                23.2
pandas                   2.1.1
pbr                      5.11.1
peakdetect               1.2
Pillow                   10.0.1
pip                      23.3
protobuf                 4.24.4
pyasn1                   0.5.0
pyasn1-modules           0.3.0
Pygments                 2.16.1
pyparsing                3.1.1
PyQt6                    6.5.3
PyQt6-Qt6                6.5.3
PyQt6-sip                13.6.0
pyqtgraph                0.13.3
python-dateutil          2.8.2
pytz                     2023.3.post1
PyYAML                   6.0.1
QtPy                     2.4.1
requests                 2.31.0
rsa                      4.9
scikit-image             0.22.0
scikit-learn             1.3.2
scipy                    1.11.3
setuptools               68.0.0
six                      1.16.0
superqt                  0.6.1
sympy                    1.12
texttable                1.7.0
threadpoolctl            3.2.0
tifffile                 2023.9.26
torch                    2.0.1
torchvf                  0.1.3
torchvision              0.15.2
tqdm                     4.66.1
triton                   2.0.0
typing_extensions        4.8.0
tzdata                   2023.3
urllib3                  2.0.7
wheel                    0.41.2

```

**Comment by kevinjohncutler** [comment]
@JunMa11 Sorry for the long delay. Please let me know if you are still experiencing this issue with the latest github version.

**Comment by bentaculum** [comment]
I just had the same issue
```
omnipose
2024-03-02 13:19:24,491	[INFO ]	[io.py      60   logger_setup      ]	WRITING LOG OUTPUT TO /home/gallusse/.cellpose/run.log
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, minimalegl, vkkhrdisplay, eglfs, linuxfb, vnc, offscreen, minimal, xcb.

Aborted (core dumped)
```

and found the following fix (for Qt 6.5.0):
```
sudo apt install libxcb-cursor0
```
