### ISSUE TITLE
RuntimeError when attempting training with GPU

### ISSUE THREAD

**Issue by vhickl** [kevinjohncutler/omnipose#68]
Hi,
I'm just getting started with training my own models for Omnipose. After running into some issues I decided to make sure everything is set up correctly by just replicating the training procedure in the tutorial using the bact_phase data from the Omnipose paper. Training on CPU seems to run fine, albeit very slowly on my machinery.
I eventually got the GPU training to initialize correctly ('TORCH GPU version installed and working. \ >>>> using GPU') by following advice here:
https://forum.image.sc/t/cellpose-torch-cuda-version-not-installed-working/77390

Now I get a new error apparently related to the TorchScript interpreter. The full command I used was

omnipose --train --use_gpu --dir <dir> --mask_filter _masks --n_epochs 4000 --pretrained_model None --learning_rate 0.1 --diameter 0 --batch_size 16 --RAdam --nclasses 3 --look_one_level_down --save_every 10 --save_each --verbose

The full output is pasted below showing the error at the bottom. Is the issue with my inputs or do I need to install pytorch differently? Is the warning about pyqt5 vs 6 important? Any help would be appreciated, thanks in advance!

C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\superqt\collapsible\_collapsible.py:4: PythonQtWarning: Selected binding 'pyqt5' could not be found; falling back to 'pyqt6'
  from qtpy.QtCore import (
2023-12-07 10:30:49,772 [INFO] WRITING LOG OUTPUT TO C:\Users\hivi\.cellpose\run.log
log file C:\Users\<username>\.cellpose\run.log
2023-12-07 10:30:49,952 [INFO] ** TORCH GPU version installed and working. **
2023-12-07 10:30:49,953 [INFO] >>>> using GPU
2023-12-07 10:30:49,953 [INFO] Training omni model. Setting nclasses=3, RAdam=True
2023-12-07 10:30:52,064 [INFO] not all flows are present, will run flow generation for all images
2023-12-07 10:30:52,331 [INFO] setting nchan to 1. Be sure to use --nchan 1 when running the model.
2023-12-07 10:30:52,332 [INFO] training from scratch
2023-12-07 10:30:52,332 [INFO] median diameter set to 0 => no rescaling during training
2023-12-07 10:30:54,751 [INFO] No precomuting flows with Omnipose. Computed during training.
2023-12-07 10:30:55,437 [WARNING] channels is set to None, input must therefore have nchan channels (default is 2)
2023-12-07 10:30:55,461 [INFO] >>> Using RAdam optimizer
2023-12-07 10:30:55,461 [INFO] >>>> training network with 1 channel input <<<<
2023-12-07 10:30:55,461 [INFO] >>>> LR: 0.10000, batch_size: 16, weight_decay: 0.00001
2023-12-07 10:30:55,461 [INFO] >>>> ntrain = 249
2023-12-07 10:30:55,462 [INFO] >>>> nimg_per_epoch = 249
2023-12-07 10:30:59,752 [INFO] >>>> Start time: 10:30:59
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\h<username>\AppData\Local\anaconda3\envs\omnipose\Scripts\omnipose.exe\__main__.py", line 7, in <module>
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\omnipose\__main__.py", line 9, in main
    cellpose_omni_main(args)
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\cellpose_omni\__main__.py", line 439, in main
    cpmodel_path = model.train(images, labels, links, train_files=image_names,
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\cellpose_omni\models.py", line 1572, in train
    model_path = self._train_net(train_data, train_labels, train_links,
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\cellpose_omni\core.py", line 1157, in _train_net
    out = omnipose.core.masks_to_flows_batch(lbl, links,
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\omnipose\core.py", line 449, in masks_to_flows_batch
    T, mu = masks_to_flows_torch(clabels, affinity_graph, ccoords,
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\omnipose\core.py", line 600, in masks_to_flows_torch
    out = _extend_centers_torch(masks, centers, affinity_graph, coords,
  File "C:\Users\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\omnipose\core.py", line 1009, in _extend_centers_torch
    T = _iterate(T,neigh_inds,central_inds,centroid_inds,
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "C:\Users\\<username>\AppData\Local\anaconda3\envs\omnipose\lib\site-packages\omnipose\core.py", line 1129, in _iterate
    while not_converged:
        if omni:# and OMNI_INSTALLED:
            Tneigh = T[neigh_inds]
                     ~~~~~~~~~~~~~ <--- HERE
            Tneigh *= isneigh #zeros out any elements that do not belong in convolution
            T = eikonal_update_torch(Tneigh,r,d,inds,fact) # now central_inds = 0,1,2,3,...
RuntimeError: tensors used as indices must be long, byte or bool tensors

**Comment by vhickl** [comment]
I might have found a fix for this. I went into the core.py code and appended ".long()" to several tensor indices to turn them into long tensor. 

I made changes to lines 1129, 1148, 1180, and 1201 (twice), and 1205.

After that the training seemed to proceed with no further warnings using the GPU. 

However, when I try to actually use the resulting model (which should be identical to the pretrained bact_phase_omni model) I get the same error described in issue #69 posted the day after mine by 73Emilie:

Thus I can't say with certainty that my ad hoc solution worked.

**Comment by vhickl** [comment]
Ok turns out the second issue was caused by me incorrectly setting nchan during segmentation. Now my retrained version of bact_phase_omni seems to work as expected.

Still feels strange that I had to change those variables types but the issue seems solved for now.
