### ISSUE TITLE
Error: `ModuleNotFoundError: No module named 'aicsimageio'`

### ISSUE THREAD

**Issue by ElpadoCan** [kevinjohncutler/omnipose#80]
I installed omnipose by cloning and running `pip install -e .`  and I got the following error. I know I can fix by installing `aicsimageio` but I just wanted to let you know, thanks! 

```
Traceback (most recent call last):
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\elpad\.virtualenvs\omnipose-dev\Scripts\omnipose.exe\__main__.py", line 4, in <module>
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\omnipose\omnipose\__init__.py", line 1, in <module>
    from . import core, utils, loss, plot, misc, cli, data, gpu
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\omnipose\omnipose\data.py", line 13, in <module>
    from aicsimageio import AICSImage
ModuleNotFoundError: No module named 'aicsimageio'
```

**Comment by kevinjohncutler** [comment]
Sorry about that, just pushed the update to fix the import.
