### ISSUE TITLE
 Cellpose Extension 0.9.3 for QuPath 0.5.1 Training - Code ERROR 

### ISSUE THREAD

**Issue by marciaazevedo** [kevinjohncutler/omnipose#95]
Dear all,

I am trying to use CellPose extension in QuPath to train a model for my tissues. I am using QuPath 0.5.1 with CellPost extension 0.9.3.

I used 2 images, both annotated with 2 “training” and 2 “validation” annotations and drew my ground truth annotations within all of the rectangles as recommended in [https://github.com/BIOP/qupath-extension-cellpose](https://github.com/BIOP/qupath-extension-cellpose). However, when I run the Cellpose Training Template script as below:

```
// First we need to create a Cellpose2D builder and add all parameters that we want to use for training
def cellpose = Cellpose2D.builder(“None”) // Can choose “None” if you want to train from scratch
.channels(“CTB”) // or work with .cellposeChannels( channel1, channel2 ) and follow the cellpose way
// .preprocess(ImageOps.Filters.gaussianBlur(1)) // Optional preprocessing QuPath Ops
// .epochs(500) // Optional: will default to 500
// .groundTruthDirectory( new File(“/my/ground/truth/folder”)) // Optional: If you wish to save your GT elsewhere than the QuPath Project
// .learningRate(0.2) // Optional: Will default to 0.2
// .batchSize(8) // Optional: Will default to 8
// .minTrainMasks(5) // Optional: Will default to 5
// .addParameter(“save_flows”) // Any parameter from cellpose not available in the builder. See Command line — cellpose 3.0.8-8-gc03958c documentation
// .addParameter(“anisotropy”, “3”) // Any parameter from cellpose not available in the builder. See Command line — cellpose 3.0.8-8-gc03958c documentation
// .modelDirectory( new File(“My/folder/for/models”)) // Optional place to store resulting model. Will default to QuPath project root, and make a ‘models’ folder
// .saveBuilder(“My Builder”) // Optional: Will save a builder json file that can be reloaded with Cellpose2D.builder(File builderFile)
.build()

// Now we can train a new model
def resultModel = cellpose.train()

// Pick up results to see how the training was performed
println "Model Saved under: "
println resultModel.getAbsolutePath().toString().replace(‘\’, ‘/’) // To make it easier to copy paste in windows

// You can get a ResultsTable of the training.
def results = cellpose.getTrainingResults()
results.show(“Training Results”)

// You can get a results table with the QC results to visualize
def qcResults = cellpose.getQCResults()
qcResults.show(“QC Results”)

// Finally you have access to a very simple graph of the loss during training
cellpose.showTrainingGraph()

println “Training Script Finished”

import qupath.ext.biop.cellpose.Cellpose2D
```

I keep getting this error:

```
INFO: Neither diameter nor overlap provided. Overlap defaulting to 60 pixels. Use .setOverlap( int ) to modify overlap
INFO: If tiling is necessary, 60 pixels overlap will be taken between tiles
INFO: Found 2 Training objects and 2 Validation objects in image P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1
INFO: Saved image pair:
P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1_region_0.tif
P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1_region_0_masks.tif
INFO: Saved image pair:
P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1_region_1.tif
P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1_region_1_masks.tif
INFO: Saved image pair:
P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1_region_0.tif
P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1_region_0_masks.tif
INFO: Saved image pair:
P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1_region_1.tif
P2819_10M 20x overview_FusionStitcher.ims - P2819_10M 20x overview_FusionStitcher.ims Resolution Level 1_region_1_masks.tif
INFO: Found 2 Training objects and 2 Validation objects in image P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1
INFO: Saved image pair:
P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1_region_0.tif
P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1_region_0_masks.tif
INFO: Saved image pair:
P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1_region_1.tif
P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1_region_1_masks.tif
INFO: Saved image pair:
P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1_region_0.tif
P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1_region_0_masks.tif
INFO: Saved image pair:
P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1_region_1.tif
P2822_3M 20x cortex_1_FusionStitcher.ims - P2822_3M 20x cortex_1_FusionStitcher.ims Resolution Level 1_region_1_masks.tif
INFO: Executing command:
cmd.exe /C C:\Users\neves\anaconda3\envs\cellpose\python.exe -Xutf8 -W ignore -m cellpose --train --dir “C:\Users\neves\OneDrive - Universidade de Aveiro\Documents\Mestrado em Biomedicina Molecular\2º ano\Tese\QuPath\Training images\Emptyfolder project\cellpose-training\train” --test_dir “C:\Users\neves\OneDrive - Universidade de Aveiro\Documents\Mestrado em Biomedicina Molecular\2º ano\Tese\QuPath\Training images\Emptyfolder project\cellpose-training\test” --pretrained_model None --use_gpu --verbose
INFO: This command should run directly if copy-pasted into your shell
INFO: Virtual Environment Runner Started
INFO: Cellpose2D: 2024-06-03 22:44:37,458 [INFO] WRITING LOG OUTPUT TO C:\Users\neves.cellpose\run.log
INFO: Cellpose2D: 2024-06-03 22:44:37,458 [INFO]
INFO: Cellpose2D: cellpose version: 3.0.8
INFO: Cellpose2D: platform: win32
INFO: Cellpose2D: python version: 3.8.19
INFO: Cellpose2D: torch version: 2.3.0+cpu
INFO: Cellpose2D: 2024-06-03 22:44:37,477 [INFO] TORCH CUDA version not installed/working.
INFO: Cellpose2D: 2024-06-03 22:44:37,478 [INFO] >>>> using CPU
INFO: Cellpose2D: 2024-06-03 22:44:37,485 [INFO] not all flows are present, running flow generation for all images
INFO: Cellpose2D: Traceback (most recent call last):
INFO: Cellpose2D: File “C:\Users\neves\anaconda3\envs\cellpose\lib\runpy.py”, line 194, in _run_module_as_main
INFO: Cellpose2D: return run_code(code, main_globals, None,
INFO: Cellpose2D: File “C:\Users\neves\anaconda3\envs\cellpose\lib\runpy.py”, line 87, in run_code
INFO: Cellpose2D: exec(code, run_globals)
INFO: Cellpose2D: File "C:\Users\neves\anaconda3\envs\cellpose\lib\site-packages\cellpose_main.py", line 348, in
INFO: Cellpose2D: main()
INFO: Cellpose2D: File "C:\Users\neves\anaconda3\envs\cellpose\lib\site-packages\cellpose_main.py", line 252, in main
INFO: Cellpose2D: output = io.load_train_test_data(args.dir, test_dir, imf, args.mask_filter,
INFO: Cellpose2D: File “C:\Users\neves\anaconda3\envs\cellpose\lib\site-packages\cellpose\io.py”, line 461, in load_train_test_data
INFO: Cellpose2D: images, labels, image_names = load_images_labels(train_dir, mask_filter,
INFO: Cellpose2D: File “C:\Users\neves\anaconda3\envs\cellpose\lib\site-packages\cellpose\io.py”, line 418, in load_images_labels
INFO: Cellpose2D: label_names, flow_names = get_label_files(image_names, mask_filter,
INFO: Cellpose2D: File “C:\Users\neves\anaconda3\envs\cellpose\lib\site-packages\cellpose\io.py”, line 387, in get_label_files
INFO: Cellpose2D: raise ValueError(“labels not provided with correct --mask_filter”)
INFO: Cellpose2D: ValueError: labels not provided with correct --mask_filter
ERROR: null in QuPathScript at line number 35
java.base/java.util.Objects.requireNonNull(Unknown Source)
qupath.ext.biop.cellpose.Cellpose2D.moveAndReturnModelFile(Cellpose2D.java:1327)
qupath.ext.biop.cellpose.Cellpose2D.train(Cellpose2D.java:883)
org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
QuPathScript.run(QuPathScript:35)
org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:331)
org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:161)
qupath.lib.gui.scripting.languages.DefaultScriptLanguage.execute(DefaultScriptLanguage.java:234)
qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:1166)
qupath.lib.gui.scripting.DefaultScriptEditor$3.run(DefaultScriptEditor.java:1534)
java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
java.base/java.util.concurrent.FutureTask.run(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.base/java.lang.Thread.run(Unknown Source)
```

I was wondering if someone could kindly help me with this error: ValueError: labels not provided with correct --mask_filter
ERROR: null in QuPathScript at line number 35

Thank you very much.
Márcia

**Comment by kevinjohncutler** [comment]
@marciaazevedo Sorry, I'd like to help but I don't have the bandwidth to look into qupath. Hopefully someone over in the cellpose repo can help! A couple thoughts from the logs: go ahead and follow the docs to train outside of qupath, just in CLI, and just use all your data for training (don't use any for validation until you have a good model as a basis to make more annotations). It appears that the mask filter is wrong, so make sure you have the directory set up right. I may lay it out more explicitly in my [docs](https://omnipose.readthedocs.io/training.html#training-data) than in the cellpose docs.
